name: GitHub Actions Demo
run-name: ${{ github.actor }} pushed a change 🚀
on: [push]
jobs:
  Test-And-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright
        run: npx playwright install chromium
      - name: Run system tests
        run: yarn test:system
      - name: Upload Playwright results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Build application
        run: yarn build