name: GitHub Actions Demo
run-name: ${{ github.actor }} pushed a change 🚀
on: [push]
jobs:
  Test-And-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: yarn test:unit
      - name: Install Playwright
        run: npx playwright install chromium
      - name: Run component tests
        id: componentTests
        run: yarn test:component
      - name: Upload component test execution results
        uses: actions/upload-artifact@v3
        if: failure() && steps.componentTests.outcome == 'failure'
        with:
          name: component-tests-report
          path: test/component/playwright-report/
          retention-days: 30
      - name: Run system tests
        id: systemTests
        run: yarn test:system
      - name: Upload system test execution results
        uses: actions/upload-artifact@v3
        if: failure() && steps.systemTests.outcome == 'failure'
        with:
          name: system-tests-report
          path: test/system/playwright-report/
          retention-days: 30
      - name: Build application
        run: yarn build